include("scripts.entities.cursed_gaper")
include("scripts.entities.cursed_fatty")
include("scripts.entities.cursed_keeper_head")
include("scripts.entities.cursed_horf")
include("scripts.entities.cursed_psy_horf")
include("scripts.entities.cursed_moms_hand")
include("scripts.entities.hunter")
include("scripts.entities.holy_portal")
include("scripts.entities.holy_brain")
include("scripts.entities.cursed_haunt")
include("scripts.entities.coil")
include("scripts.entities.weltling")
include("scripts.entities.blank_canvas_mulligan")
include("scripts.entities.blank_canvas_gaper")
include("scripts.entities.blank_canvas_fly")
include("scripts.entities.blank_canvas_pooter")
include("scripts.entities.blank_canvas_tear")
include("scripts.entities.blank_canvas_dip")
include("scripts.entities.holy_psy_horf")
include("scripts.entities.proglottid_egg")
include("scripts.entities.isaac_enemy")

include("scripts.effects.stun_tentacle")

include("scripts.entities.resouled_dummy")
include("scripts.entities.resouled_hitbox")
include("scripts.entities.buff_pedestal")

include("scripts.entities.lightswitch")
