include("scripts.pickups.BaseGameV2.triple_coin")
include("scripts.pickups.BaseGameV2.quad_coin")
include("scripts.pickups.blast_miner_tnt")
include("scripts.pickups.magic_marker")
include("scripts.pickups.soul")